import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  javascript: [
    {
      type: "category",
      label: "JavaScript",
      link: {
        type: "generated-index",
      },
      collapsible: false,
      items: [
        {
          type: "autogenerated",
          dirName: "javascript", // '.' 即当前的文档文件夹
        },
      ],
    },
  ],
  typescript: [
    {
      type: "category",
      label: "TypeScript",
      link: {
        type: "generated-index",
        slug: "/typescript",
      },
      items: [
        {
          type: "autogenerated",
          dirName: "typescript", // '.' 即当前的文档文件夹
        },
      ],
    },
  ],
  css: [
    {
      type: "category",
      label: "CSS",
      link: {
        type: "generated-index",
      },
      collapsible: false,
      items: [
        {
          type: "autogenerated",
          dirName: "css", // '.' 即当前的文档文件夹
        },
      ],
    },
  ],
  react: [
    {
      type: "category",
      label: "React",
      link: {
        type: "generated-index",
      },
      collapsible: false,
      items: [
        {
          type: "autogenerated",
          dirName: "react", // '.' 即当前的文档文件夹
        },
      ],
    },
  ],
  algorithm: [
    {
      type: "autogenerated",
      dirName: "algorithm",
    },
  ],
  engineer: [
    {
      type: "category",
      label: "前端工程化体系",
      link: {
        type: "generated-index",
      },
      collapsible: false,
      items: [
        {
          type: "autogenerated",
          dirName: "engineer", // '.' 即当前的文档文件夹
        },
      ],
    },
  ],
  network: [
    {
      type: "category",
      label: "Network",
      link: { type: "doc", id: "network/index" },
      collapsible: false,
      items: [
        {
          type: "category",
          label: "应用层",
          link: {
            type: "generated-index",
          },
          items: [
            {
              type: "autogenerated",
              dirName: "network/应用层", // '.' 即当前的文档文件夹
            },
          ],
        },
        {
          type: "category",
          label: "运输层",
          link: {
            type: "generated-index",
          },
          items: [
            {
              type: "autogenerated",
              dirName: "network/运输层", // '.' 即当前的文档文件夹
            },
          ],
        },
        {
          type: "doc",
          id: "network/网速与带宽", // '.' 即当前的文档文件夹
        },
      ],
    },
  ],
  nodejs: [
    {
      type: "category",
      label: "Node",
      link: {
        type: "generated-index",
      },
      items: [
        {
          type: "autogenerated",
          dirName: "nodejs", // '.' 即当前的文档文件夹
        },
      ],
    },
  ],
  tools: [
    {
      type: "category",
      label: "Tool",
      link: {
        type: "generated-index",
      },
      items: [
        {
          type: "autogenerated",
          dirName: "tools", // '.' 即当前的文档文件夹
        },
      ],
    },
  ],
  interview: [
    {
      type: "category",
      label: "Interview",
      link: { type: "doc", id: "interview/index" },
      collapsible: false,
      items: [
        {
          type: "doc",
          id: "interview/js",
        },
        {
          type: "doc",
          id: "interview/css",
        },
        {
          type: "doc",
          id: "interview/html",
        },
        {
          type: "doc",
          id: "interview/计算机网络",
        },
        {
          type: "doc",
          id: "interview/算法",
        },
      ],
    },
  ],
  prompt: [
    {
      type: "category",
      label: "Prompt",
      link: {
        type: "generated-index",
      },
      items: [
        {
          type: "autogenerated",
          dirName: "prompt", // '.' 即当前的文档文件夹
        },
      ],
    },
  ],
};

export default sidebars;
