// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  javascript: [
    {
      type: "autogenerated",
      dirName: "javascript",
    },
  ],
  typescript: [
    {
      type: "autogenerated",
      dirName: "typescript",
    },
  ],
  css: [
    {
      type: "autogenerated",
      dirName: "css",
    },
  ],
  react: [
    {
      type: "autogenerated",
      dirName: "react",
    },
  ],
  algorithm: [
    {
      type: "autogenerated",
      dirName: "algorithm",
    },
  ],
  engineer: [
    {
      type: "autogenerated",
      dirName: "engineer",
    },
  ],
  network: [
    {
      type: "autogenerated",
      dirName: "network",
    },
  ],
  nodejs: [
    {
      type: "autogenerated",
      dirName: "nodejs",
    },
  ],
  tools: [
    {
      type: "autogenerated",
      dirName: "tools",
    },
  ],
};

module.exports = sidebars;
